on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Check formatting
      if: github.event_name == 'push' && matrix.os == 'ubuntu-latest'
      run: .github/workflows/check_formatting.sh
    - name: Test
      run: |
        export GO111MODULE=on
        go test ./...
        go test -race ./...
